FROM node:18.16.0
#dependencias
RUN apt-get update && \
    apt-get install -y \
    python2 \
    make \
    g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/backend
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3001
CMD [ "npm", "start"]
